version: '3.8' # Use a recent Docker Compose file format version

services:
  database_service: # the name of the service
    image: postgres:17 # Or the latest version, e.g., postgres:latest
    container_name: database_container # set the container_name
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD} # use the value of DB_PASSWORD in the .env file in the same directory as this file
      POSTGRES_USER: root_user # set the name of the root user
      POSTGRES_DB: database # define the name of the database that your application will use
    volumes:
      - database_volume:/var/lib/postgresql/data # Mount the named volume
      - ./initialization:/docker-entrypoint-initdb.d/ # Place all initilization scripts in the folder initialization
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf # cannot use - ./config:/etc/postgresql/ otherwise the whole directory will be overridden
      - ./config/pg_hba.conf:/etc/postgresql/pg_hba.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root_user -d database"] # -U POSTGRES_USER -d POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped # Always restart unless explicitly stopped

volumes:
  database_volume: # Define the volume name
